AWSTemplateFormatVersion: 2010-09-09
Description: AWS Lambda function that uses Neptune Gremlin Client to query Amazon Neptune

Parameters:
  NeptuneClusterId:
    Description: Amazon Neptune DB cluster identifier.
    Type: String
  
  NeptunePrivateSubnet1:
    Description: Private subnet ID.
    Type: AWS::EC2::Subnet::Id
  
  NeptunePrivateSubnet2:
    Description: Private subnet ID.
    Type: AWS::EC2::Subnet::Id
  
  NeptuneVPC:
    Description: VPC ID.
    Type: AWS::EC2::VPC::Id
  
  NeptuneSecurityGroupId:
    Description: ID of a security group that the Lambda functions can use to access Neptune
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  LambdaSelfReferencingSecurityGroup:
    Properties:
      GroupDescription: Self-referencing security group for Lambda
      VpcId:
        Ref: NeptuneVPC
    Type: AWS::EC2::SecurityGroup
  
  LambdaSelfReferencingSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: LambdaSelfReferencingSecurityGroup
    Properties:
      GroupId:
        Fn::GetAtt:
          - LambdaSelfReferencingSecurityGroup
          - GroupId
      SourceSecurityGroupId:
        Fn::GetAtt:
          - LambdaSelfReferencingSecurityGroup
          - GroupId
      IpProtocol: "-1"
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                  - cloudwatch:*
                  - lambda:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - neptune-db:*
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:neptune-db:"
                      - Ref: AWS::Region
                      - ":"
                      - Ref: AWS::AccountId
                      - :*/*
  
  NeptuneGremlinLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: neptune-gremlin_${NeptuneClusterId}
      Handler: lambdaHandler #not sure on this yet
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Code: #not sure on this yet
      #Environment:
      #  Variables:
      #    neptuneEndpointsInfoLambda:
      #      Fn::Sub: neptune-endpoint-info_${NeptuneClusterId}
      MemorySize: 128
      Runtime: java8
      Timeout: "30"
      VpcConfig:
        SecurityGroupIds:
          - Ref: LambdaSelfReferencingSecurityGroup
          - Ref: NeptuneSecurityGroupId
        SubnetIds:
          - Ref: NeptunePrivateSubnet1
          - Ref: NeptunePrivateSubnet2

Outputs:
  NeptuneGremlinClientExampleLambdaArn:
    Description: NeptuneGremlinClientExampleLambda ARN
    Value:
      Fn::GetAtt:
        - NeptuneGremlinClientExampleLambda
        - Arn
